title: Developer Marketing, Developer Relations, Developer Experience, Developer Community and Events as a Service
description: Developer Marketing, Virtual Developer Meetups, Developer Relations Program Outsourcing # this means to ignore newlines until "baseurl:"  configyml
permalink: ':title/'
baseurl: # "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: http://devrel.events # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: iwozik #if your site has a twitter account, enter it here

# Author Settings
author: DevRel Events # add your name
author-img: about-128.png # add your photo
about-author: We're solving the challenge of developer marketing to game developers. 
social-twitter: iwozik # add your Twitter handle
social-facebook: devrelevents # add your Facebook handle
social-github: tooevangelist # add your Github handle
social-linkedin: pridiuk # add your Linkedin handle
social-email: devrel.events@gmail.com # add your Email address

# Disqus
discus-identifier: # mr-brown # add your discus identifier

# Tracker
analytics: UA-156909954-2 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji


paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

remote_theme: tooevangelist/flexible-jekyll
